// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package openapi

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for AccountType.
const (
	AccountTypeAsset     AccountType = "asset"
	AccountTypeEquity    AccountType = "equity"
	AccountTypeExpense   AccountType = "expense"
	AccountTypeIncome    AccountType = "income"
	AccountTypeLiability AccountType = "liability"
)

// Valid indicates whether the value is a known member of the AccountType enum.
func (e AccountType) Valid() bool {
	switch e {
	case AccountTypeAsset:
		return true
	case AccountTypeEquity:
		return true
	case AccountTypeExpense:
		return true
	case AccountTypeIncome:
		return true
	case AccountTypeLiability:
		return true
	default:
		return false
	}
}

// Defines values for CreateAccountRequestType.
const (
	CreateAccountRequestTypeAsset     CreateAccountRequestType = "asset"
	CreateAccountRequestTypeEquity    CreateAccountRequestType = "equity"
	CreateAccountRequestTypeExpense   CreateAccountRequestType = "expense"
	CreateAccountRequestTypeIncome    CreateAccountRequestType = "income"
	CreateAccountRequestTypeLiability CreateAccountRequestType = "liability"
)

// Valid indicates whether the value is a known member of the CreateAccountRequestType enum.
func (e CreateAccountRequestType) Valid() bool {
	switch e {
	case CreateAccountRequestTypeAsset:
		return true
	case CreateAccountRequestTypeEquity:
		return true
	case CreateAccountRequestTypeExpense:
		return true
	case CreateAccountRequestTypeIncome:
		return true
	case CreateAccountRequestTypeLiability:
		return true
	default:
		return false
	}
}

// Defines values for CreateMemberRequestRole.
const (
	CreateMemberRequestRoleMember CreateMemberRequestRole = "member"
	CreateMemberRequestRoleOwner  CreateMemberRequestRole = "owner"
	CreateMemberRequestRoleViewer CreateMemberRequestRole = "viewer"
)

// Valid indicates whether the value is a known member of the CreateMemberRequestRole enum.
func (e CreateMemberRequestRole) Valid() bool {
	switch e {
	case CreateMemberRequestRoleMember:
		return true
	case CreateMemberRequestRoleOwner:
		return true
	case CreateMemberRequestRoleViewer:
		return true
	default:
		return false
	}
}

// Defines values for MemberRole.
const (
	MemberRoleMember MemberRole = "member"
	MemberRoleOwner  MemberRole = "owner"
	MemberRoleViewer MemberRole = "viewer"
)

// Valid indicates whether the value is a known member of the MemberRole enum.
func (e MemberRole) Valid() bool {
	switch e {
	case MemberRoleMember:
		return true
	case MemberRoleOwner:
		return true
	case MemberRoleViewer:
		return true
	default:
		return false
	}
}

// Defines values for UpdateMemberRequestRole.
const (
	UpdateMemberRequestRoleMember UpdateMemberRequestRole = "member"
	UpdateMemberRequestRoleOwner  UpdateMemberRequestRole = "owner"
	UpdateMemberRequestRoleViewer UpdateMemberRequestRole = "viewer"
)

// Valid indicates whether the value is a known member of the UpdateMemberRequestRole enum.
func (e UpdateMemberRequestRole) Valid() bool {
	switch e {
	case UpdateMemberRequestRoleMember:
		return true
	case UpdateMemberRequestRoleOwner:
		return true
	case UpdateMemberRequestRoleViewer:
		return true
	default:
		return false
	}
}

// Account defines model for Account.
type Account struct {
	CreatedAt     time.Time   `json:"created_at"`
	Currency      string      `json:"currency"`
	HouseholdId   string      `json:"household_id"`
	Id            string      `json:"id"`
	IsPlaceholder bool        `json:"is_placeholder"`
	Name          string      `json:"name"`
	ParentId      *string     `json:"parent_id,omitempty"`
	Type          AccountType `json:"type"`
}

// AccountType defines model for Account.Type.
type AccountType string

// AccountBalance defines model for AccountBalance.
type AccountBalance struct {
	AccountId string    `json:"account_id"`
	AsOf      time.Time `json:"as_of"`

	// Balance Decimal string, e.g. "1234.56"
	Balance  string `json:"balance"`
	Currency string `json:"currency"`
}

// AccountList defines model for AccountList.
type AccountList struct {
	Data []Account `json:"data"`
	Meta Meta      `json:"meta"`
}

// BalanceSheet defines model for BalanceSheet.
type BalanceSheet struct {
	AsOf  time.Time          `json:"as_of"`
	Lines []BalanceSheetLine `json:"lines"`
}

// BalanceSheetLine defines model for BalanceSheetLine.
type BalanceSheetLine struct {
	AccountId string `json:"account_id"`

	// Balance Decimal string
	Balance  string `json:"balance"`
	Currency string `json:"currency"`
	Name     string `json:"name"`
	Type     string `json:"type"`
}

// CreateAccountRequest defines model for CreateAccountRequest.
type CreateAccountRequest struct {
	Currency      string                   `json:"currency"`
	Id            string                   `json:"id"`
	IsPlaceholder *bool                    `json:"is_placeholder,omitempty"`
	Name          string                   `json:"name"`
	ParentId      *string                  `json:"parent_id,omitempty"`
	Type          CreateAccountRequestType `json:"type"`
}

// CreateAccountRequestType defines model for CreateAccountRequest.Type.
type CreateAccountRequestType string

// CreateFiscalPeriodRequest defines model for CreateFiscalPeriodRequest.
type CreateFiscalPeriodRequest struct {
	EndDate   openapi_types.Date `json:"end_date"`
	Id        string             `json:"id"`
	Name      string             `json:"name"`
	StartDate openapi_types.Date `json:"start_date"`
}

// CreateJournalEntryRequest defines model for CreateJournalEntryRequest.
type CreateJournalEntryRequest struct {
	Description string         `json:"description"`
	Id          string         `json:"id"`
	PostedAt    time.Time      `json:"posted_at"`
	Postings    []PostingInput `json:"postings"`
	Reference   *string        `json:"reference,omitempty"`
}

// CreateMemberRequest defines model for CreateMemberRequest.
type CreateMemberRequest struct {
	DisplayName string                  `json:"display_name"`
	Email       openapi_types.Email     `json:"email"`
	Password    string                  `json:"password"`
	Role        CreateMemberRequestRole `json:"role"`
}

// CreateMemberRequestRole defines model for CreateMemberRequest.Role.
type CreateMemberRequestRole string

// FiscalPeriod defines model for FiscalPeriod.
type FiscalPeriod struct {
	EndDate     openapi_types.Date `json:"end_date"`
	HouseholdId string             `json:"household_id"`
	Id          string             `json:"id"`
	LockedAt    *time.Time         `json:"locked_at,omitempty"`
	Name        string             `json:"name"`
	StartDate   openapi_types.Date `json:"start_date"`
}

// FiscalPeriodList defines model for FiscalPeriodList.
type FiscalPeriodList struct {
	Data []FiscalPeriod `json:"data"`
	Meta Meta           `json:"meta"`
}

// HearthError defines model for HearthError.
type HearthError struct {
	Code    string    `json:"code"`
	Help    *string   `json:"help,omitempty"`
	Hints   *[]string `json:"hints,omitempty"`
	Message string    `json:"message"`
}

// Household defines model for Household.
type Household struct {
	BaseCurrency string    `json:"base_currency"`
	CreatedAt    time.Time `json:"created_at"`
	Id           string    `json:"id"`
	Name         string    `json:"name"`
}

// IncomeStatement defines model for IncomeStatement.
type IncomeStatement struct {
	After  time.Time             `json:"after"`
	Before time.Time             `json:"before"`
	Lines  []IncomeStatementLine `json:"lines"`
}

// IncomeStatementLine defines model for IncomeStatementLine.
type IncomeStatementLine struct {
	AccountId string `json:"account_id"`

	// Balance Decimal string
	Balance  string `json:"balance"`
	Currency string `json:"currency"`
	Name     string `json:"name"`
	Type     string `json:"type"`
}

// JournalEntry defines model for JournalEntry.
type JournalEntry struct {
	CreatedBy    string    `json:"created_by"`
	Description  string    `json:"description"`
	HouseholdId  string    `json:"household_id"`
	Id           string    `json:"id"`
	IsReversalOf *string   `json:"is_reversal_of,omitempty"`
	PostedAt     time.Time `json:"posted_at"`
	Postings     []Posting `json:"postings"`
	Reference    *string   `json:"reference,omitempty"`
	Source       string    `json:"source"`
}

// JournalEntryList defines model for JournalEntryList.
type JournalEntryList struct {
	Data []JournalEntry `json:"data"`
	Meta Meta           `json:"meta"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email       openapi_types.Email `json:"email"`
	HouseholdId string              `json:"household_id"`
	Password    string              `json:"password"`
}

// LogoutRequest defines model for LogoutRequest.
type LogoutRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// Member defines model for Member.
type Member struct {
	CreatedAt   time.Time           `json:"created_at"`
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	HouseholdId string              `json:"household_id"`
	Id          string              `json:"id"`
	Role        MemberRole          `json:"role"`
}

// MemberRole defines model for Member.Role.
type MemberRole string

// MemberList defines model for MemberList.
type MemberList struct {
	Data []Member `json:"data"`
	Meta Meta     `json:"meta"`
}

// Meta defines model for Meta.
type Meta struct {
	Limit  int `json:"limit"`
	Offset int `json:"offset"`
	Total  int `json:"total"`
}

// Posting defines model for Posting.
type Posting struct {
	AccountId string `json:"account_id"`

	// Amount Decimal string; positive = debit, negative = credit
	Amount   string  `json:"amount"`
	Currency string  `json:"currency"`
	Id       string  `json:"id"`
	Memo     *string `json:"memo,omitempty"`
}

// PostingInput defines model for PostingInput.
type PostingInput struct {
	AccountId string `json:"account_id"`

	// Amount Decimal string
	Amount   string  `json:"amount"`
	Currency string  `json:"currency"`
	Id       string  `json:"id"`
	Memo     *string `json:"memo,omitempty"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// TokenPair defines model for TokenPair.
type TokenPair struct {
	AccessToken string `json:"access_token"`

	// ExpiresIn Access token lifetime in seconds
	ExpiresIn    int    `json:"expires_in"`
	RefreshToken string `json:"refresh_token"`
}

// UpdateAccountRequest defines model for UpdateAccountRequest.
type UpdateAccountRequest struct {
	IsPlaceholder *bool   `json:"is_placeholder,omitempty"`
	Name          *string `json:"name,omitempty"`
}

// UpdateHouseholdRequest defines model for UpdateHouseholdRequest.
type UpdateHouseholdRequest struct {
	Name *string `json:"name,omitempty"`
}

// UpdateMemberRequest defines model for UpdateMemberRequest.
type UpdateMemberRequest struct {
	Role UpdateMemberRequestRole `json:"role"`
}

// UpdateMemberRequestRole defines model for UpdateMemberRequest.Role.
type UpdateMemberRequestRole string

// Conflict defines model for Conflict.
type Conflict = HearthError

// Forbidden defines model for Forbidden.
type Forbidden = HearthError

// NotFound defines model for NotFound.
type NotFound = HearthError

// Unauthorized defines model for Unauthorized.
type Unauthorized = HearthError

// UnprocessableEntity defines model for UnprocessableEntity.
type UnprocessableEntity = HearthError

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// GetAccountBalanceParams defines parameters for GetAccountBalance.
type GetAccountBalanceParams struct {
	// AsOf Balance as of this timestamp (RFC 3339); defaults to now
	AsOf *time.Time `form:"as_of,omitempty" json:"as_of,omitempty"`
}

// ListJournalEntriesParams defines parameters for ListJournalEntries.
type ListJournalEntriesParams struct {
	Limit           *int       `form:"limit,omitempty" json:"limit,omitempty"`
	Offset          *int       `form:"offset,omitempty" json:"offset,omitempty"`
	AccountId       *string    `form:"account_id,omitempty" json:"account_id,omitempty"`
	After           *time.Time `form:"after,omitempty" json:"after,omitempty"`
	Before          *time.Time `form:"before,omitempty" json:"before,omitempty"`
	DescriptionLike *string    `form:"description_like,omitempty" json:"description_like,omitempty"`
}

// CreateJournalEntryParams defines parameters for CreateJournalEntry.
type CreateJournalEntryParams struct {
	Limit           *int       `form:"limit,omitempty" json:"limit,omitempty"`
	Offset          *int       `form:"offset,omitempty" json:"offset,omitempty"`
	AccountId       *string    `form:"account_id,omitempty" json:"account_id,omitempty"`
	After           *time.Time `form:"after,omitempty" json:"after,omitempty"`
	Before          *time.Time `form:"before,omitempty" json:"before,omitempty"`
	DescriptionLike *string    `form:"description_like,omitempty" json:"description_like,omitempty"`
}

// GetBalanceSheetParams defines parameters for GetBalanceSheet.
type GetBalanceSheetParams struct {
	AsOf *time.Time `form:"as_of,omitempty" json:"as_of,omitempty"`
}

// GetIncomeStatementParams defines parameters for GetIncomeStatement.
type GetIncomeStatementParams struct {
	After  time.Time `form:"after" json:"after"`
	Before time.Time `form:"before" json:"before"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = LogoutRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshRequest

// UpdateHouseholdJSONRequestBody defines body for UpdateHousehold for application/json ContentType.
type UpdateHouseholdJSONRequestBody = UpdateHouseholdRequest

// CreateAccountJSONRequestBody defines body for CreateAccount for application/json ContentType.
type CreateAccountJSONRequestBody = CreateAccountRequest

// UpdateAccountJSONRequestBody defines body for UpdateAccount for application/json ContentType.
type UpdateAccountJSONRequestBody = UpdateAccountRequest

// CreateJournalEntryJSONRequestBody defines body for CreateJournalEntry for application/json ContentType.
type CreateJournalEntryJSONRequestBody = CreateJournalEntryRequest

// CreateMemberJSONRequestBody defines body for CreateMember for application/json ContentType.
type CreateMemberJSONRequestBody = CreateMemberRequest

// UpdateMemberJSONRequestBody defines body for UpdateMember for application/json ContentType.
type UpdateMemberJSONRequestBody = UpdateMemberRequest

// CreateFiscalPeriodJSONRequestBody defines body for CreateFiscalPeriod for application/json ContentType.
type CreateFiscalPeriodJSONRequestBody = CreateFiscalPeriodRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Authenticate and receive a token pair
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Revoke the current refresh token
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Exchange a refresh token for a new token pair
	// (POST /auth/refresh)
	RefreshToken(w http.ResponseWriter, r *http.Request)
	// Get household details
	// (GET /households/{householdId})
	GetHousehold(w http.ResponseWriter, r *http.Request, householdId string)
	// Update household details
	// (PATCH /households/{householdId})
	UpdateHousehold(w http.ResponseWriter, r *http.Request, householdId string)
	// List accounts for a household
	// (GET /households/{householdId}/accounts)
	ListAccounts(w http.ResponseWriter, r *http.Request, householdId string)
	// Create a new account
	// (POST /households/{householdId}/accounts)
	CreateAccount(w http.ResponseWriter, r *http.Request, householdId string)
	// Get an account by ID
	// (GET /households/{householdId}/accounts/{accountId})
	GetAccount(w http.ResponseWriter, r *http.Request, householdId string, accountId string)
	// Update account name or placeholder status
	// (PATCH /households/{householdId}/accounts/{accountId})
	UpdateAccount(w http.ResponseWriter, r *http.Request, householdId string, accountId string)
	// Get the running balance of an account
	// (GET /households/{householdId}/accounts/{accountId}/balance)
	GetAccountBalance(w http.ResponseWriter, r *http.Request, householdId string, accountId string, params GetAccountBalanceParams)
	// List journal entries with optional filters
	// (GET /households/{householdId}/entries)
	ListJournalEntries(w http.ResponseWriter, r *http.Request, householdId string, params ListJournalEntriesParams)
	// Post a new journal entry
	// (POST /households/{householdId}/entries)
	CreateJournalEntry(w http.ResponseWriter, r *http.Request, householdId string, params CreateJournalEntryParams)
	// Get a journal entry by ID
	// (GET /households/{householdId}/entries/{entryId})
	GetJournalEntry(w http.ResponseWriter, r *http.Request, householdId string, entryId string)
	// Create a reversing entry for the given entry
	// (POST /households/{householdId}/entries/{entryId}/reverse)
	ReverseJournalEntry(w http.ResponseWriter, r *http.Request, householdId string, entryId string)
	// List all members of a household
	// (GET /households/{householdId}/members)
	ListMembers(w http.ResponseWriter, r *http.Request, householdId string)
	// Add a new member to the household
	// (POST /households/{householdId}/members)
	CreateMember(w http.ResponseWriter, r *http.Request, householdId string)
	// Remove a member from the household
	// (DELETE /households/{householdId}/members/{memberId})
	DeleteMember(w http.ResponseWriter, r *http.Request, householdId string, memberId string)
	// Get a member by ID
	// (GET /households/{householdId}/members/{memberId})
	GetMember(w http.ResponseWriter, r *http.Request, householdId string, memberId string)
	// Update a member's role
	// (PATCH /households/{householdId}/members/{memberId})
	UpdateMember(w http.ResponseWriter, r *http.Request, householdId string, memberId string)
	// List fiscal periods for a household
	// (GET /households/{householdId}/periods)
	ListFiscalPeriods(w http.ResponseWriter, r *http.Request, householdId string)
	// Create a fiscal period
	// (POST /households/{householdId}/periods)
	CreateFiscalPeriod(w http.ResponseWriter, r *http.Request, householdId string)
	// Lock a fiscal period (prevents new entries)
	// (POST /households/{householdId}/periods/{periodId}/lock)
	LockFiscalPeriod(w http.ResponseWriter, r *http.Request, householdId string, periodId string)
	// Balance sheet as of a given date
	// (GET /households/{householdId}/reports/balance-sheet)
	GetBalanceSheet(w http.ResponseWriter, r *http.Request, householdId string, params GetBalanceSheetParams)
	// Income statement for a date range
	// (GET /households/{householdId}/reports/income-statement)
	GetIncomeStatement(w http.ResponseWriter, r *http.Request, householdId string, params GetIncomeStatementParams)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Authenticate and receive a token pair
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke the current refresh token
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Exchange a refresh token for a new token pair
// (POST /auth/refresh)
func (_ Unimplemented) RefreshToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get household details
// (GET /households/{householdId})
func (_ Unimplemented) GetHousehold(w http.ResponseWriter, r *http.Request, householdId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update household details
// (PATCH /households/{householdId})
func (_ Unimplemented) UpdateHousehold(w http.ResponseWriter, r *http.Request, householdId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List accounts for a household
// (GET /households/{householdId}/accounts)
func (_ Unimplemented) ListAccounts(w http.ResponseWriter, r *http.Request, householdId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new account
// (POST /households/{householdId}/accounts)
func (_ Unimplemented) CreateAccount(w http.ResponseWriter, r *http.Request, householdId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get an account by ID
// (GET /households/{householdId}/accounts/{accountId})
func (_ Unimplemented) GetAccount(w http.ResponseWriter, r *http.Request, householdId string, accountId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update account name or placeholder status
// (PATCH /households/{householdId}/accounts/{accountId})
func (_ Unimplemented) UpdateAccount(w http.ResponseWriter, r *http.Request, householdId string, accountId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the running balance of an account
// (GET /households/{householdId}/accounts/{accountId}/balance)
func (_ Unimplemented) GetAccountBalance(w http.ResponseWriter, r *http.Request, householdId string, accountId string, params GetAccountBalanceParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List journal entries with optional filters
// (GET /households/{householdId}/entries)
func (_ Unimplemented) ListJournalEntries(w http.ResponseWriter, r *http.Request, householdId string, params ListJournalEntriesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Post a new journal entry
// (POST /households/{householdId}/entries)
func (_ Unimplemented) CreateJournalEntry(w http.ResponseWriter, r *http.Request, householdId string, params CreateJournalEntryParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a journal entry by ID
// (GET /households/{householdId}/entries/{entryId})
func (_ Unimplemented) GetJournalEntry(w http.ResponseWriter, r *http.Request, householdId string, entryId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a reversing entry for the given entry
// (POST /households/{householdId}/entries/{entryId}/reverse)
func (_ Unimplemented) ReverseJournalEntry(w http.ResponseWriter, r *http.Request, householdId string, entryId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all members of a household
// (GET /households/{householdId}/members)
func (_ Unimplemented) ListMembers(w http.ResponseWriter, r *http.Request, householdId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a new member to the household
// (POST /households/{householdId}/members)
func (_ Unimplemented) CreateMember(w http.ResponseWriter, r *http.Request, householdId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Remove a member from the household
// (DELETE /households/{householdId}/members/{memberId})
func (_ Unimplemented) DeleteMember(w http.ResponseWriter, r *http.Request, householdId string, memberId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a member by ID
// (GET /households/{householdId}/members/{memberId})
func (_ Unimplemented) GetMember(w http.ResponseWriter, r *http.Request, householdId string, memberId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a member's role
// (PATCH /households/{householdId}/members/{memberId})
func (_ Unimplemented) UpdateMember(w http.ResponseWriter, r *http.Request, householdId string, memberId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List fiscal periods for a household
// (GET /households/{householdId}/periods)
func (_ Unimplemented) ListFiscalPeriods(w http.ResponseWriter, r *http.Request, householdId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a fiscal period
// (POST /households/{householdId}/periods)
func (_ Unimplemented) CreateFiscalPeriod(w http.ResponseWriter, r *http.Request, householdId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Lock a fiscal period (prevents new entries)
// (POST /households/{householdId}/periods/{periodId}/lock)
func (_ Unimplemented) LockFiscalPeriod(w http.ResponseWriter, r *http.Request, householdId string, periodId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Balance sheet as of a given date
// (GET /households/{householdId}/reports/balance-sheet)
func (_ Unimplemented) GetBalanceSheet(w http.ResponseWriter, r *http.Request, householdId string, params GetBalanceSheetParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Income statement for a date range
// (GET /households/{householdId}/reports/income-statement)
func (_ Unimplemented) GetIncomeStatement(w http.ResponseWriter, r *http.Request, householdId string, params GetIncomeStatementParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHousehold operation middleware
func (siw *ServerInterfaceWrapper) GetHousehold(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "householdId" -------------
	var householdId string

	err = runtime.BindStyledParameterWithOptions("simple", "householdId", chi.URLParam(r, "householdId"), &householdId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "householdId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHousehold(w, r, householdId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateHousehold operation middleware
func (siw *ServerInterfaceWrapper) UpdateHousehold(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "householdId" -------------
	var householdId string

	err = runtime.BindStyledParameterWithOptions("simple", "householdId", chi.URLParam(r, "householdId"), &householdId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "householdId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateHousehold(w, r, householdId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAccounts operation middleware
func (siw *ServerInterfaceWrapper) ListAccounts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "householdId" -------------
	var householdId string

	err = runtime.BindStyledParameterWithOptions("simple", "householdId", chi.URLParam(r, "householdId"), &householdId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "householdId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAccounts(w, r, householdId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateAccount operation middleware
func (siw *ServerInterfaceWrapper) CreateAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "householdId" -------------
	var householdId string

	err = runtime.BindStyledParameterWithOptions("simple", "householdId", chi.URLParam(r, "householdId"), &householdId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "householdId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateAccount(w, r, householdId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAccount operation middleware
func (siw *ServerInterfaceWrapper) GetAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "householdId" -------------
	var householdId string

	err = runtime.BindStyledParameterWithOptions("simple", "householdId", chi.URLParam(r, "householdId"), &householdId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "householdId", Err: err})
		return
	}

	// ------------- Path parameter "accountId" -------------
	var accountId string

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", chi.URLParam(r, "accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccount(w, r, householdId, accountId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateAccount operation middleware
func (siw *ServerInterfaceWrapper) UpdateAccount(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "householdId" -------------
	var householdId string

	err = runtime.BindStyledParameterWithOptions("simple", "householdId", chi.URLParam(r, "householdId"), &householdId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "householdId", Err: err})
		return
	}

	// ------------- Path parameter "accountId" -------------
	var accountId string

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", chi.URLParam(r, "accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateAccount(w, r, householdId, accountId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAccountBalance operation middleware
func (siw *ServerInterfaceWrapper) GetAccountBalance(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "householdId" -------------
	var householdId string

	err = runtime.BindStyledParameterWithOptions("simple", "householdId", chi.URLParam(r, "householdId"), &householdId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "householdId", Err: err})
		return
	}

	// ------------- Path parameter "accountId" -------------
	var accountId string

	err = runtime.BindStyledParameterWithOptions("simple", "accountId", chi.URLParam(r, "accountId"), &accountId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "accountId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAccountBalanceParams

	// ------------- Optional query parameter "as_of" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "as_of", r.URL.Query(), &params.AsOf, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "as_of"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "as_of", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAccountBalance(w, r, householdId, accountId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListJournalEntries operation middleware
func (siw *ServerInterfaceWrapper) ListJournalEntries(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "householdId" -------------
	var householdId string

	err = runtime.BindStyledParameterWithOptions("simple", "householdId", chi.URLParam(r, "householdId"), &householdId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "householdId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListJournalEntriesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "account_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "account_id", r.URL.Query(), &params.AccountId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "account_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "account_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "after", r.URL.Query(), &params.After, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "after"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "before", r.URL.Query(), &params.Before, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "before"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "before", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "description_like" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "description_like", r.URL.Query(), &params.DescriptionLike, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "description_like"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "description_like", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListJournalEntries(w, r, householdId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateJournalEntry operation middleware
func (siw *ServerInterfaceWrapper) CreateJournalEntry(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "householdId" -------------
	var householdId string

	err = runtime.BindStyledParameterWithOptions("simple", "householdId", chi.URLParam(r, "householdId"), &householdId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "householdId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateJournalEntryParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "account_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "account_id", r.URL.Query(), &params.AccountId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "account_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "account_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "after" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "after", r.URL.Query(), &params.After, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "after"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "before", r.URL.Query(), &params.Before, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "before"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "before", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "description_like" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "description_like", r.URL.Query(), &params.DescriptionLike, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "description_like"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "description_like", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateJournalEntry(w, r, householdId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetJournalEntry operation middleware
func (siw *ServerInterfaceWrapper) GetJournalEntry(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "householdId" -------------
	var householdId string

	err = runtime.BindStyledParameterWithOptions("simple", "householdId", chi.URLParam(r, "householdId"), &householdId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "householdId", Err: err})
		return
	}

	// ------------- Path parameter "entryId" -------------
	var entryId string

	err = runtime.BindStyledParameterWithOptions("simple", "entryId", chi.URLParam(r, "entryId"), &entryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entryId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJournalEntry(w, r, householdId, entryId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReverseJournalEntry operation middleware
func (siw *ServerInterfaceWrapper) ReverseJournalEntry(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "householdId" -------------
	var householdId string

	err = runtime.BindStyledParameterWithOptions("simple", "householdId", chi.URLParam(r, "householdId"), &householdId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "householdId", Err: err})
		return
	}

	// ------------- Path parameter "entryId" -------------
	var entryId string

	err = runtime.BindStyledParameterWithOptions("simple", "entryId", chi.URLParam(r, "entryId"), &entryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "entryId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReverseJournalEntry(w, r, householdId, entryId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMembers operation middleware
func (siw *ServerInterfaceWrapper) ListMembers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "householdId" -------------
	var householdId string

	err = runtime.BindStyledParameterWithOptions("simple", "householdId", chi.URLParam(r, "householdId"), &householdId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "householdId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMembers(w, r, householdId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateMember operation middleware
func (siw *ServerInterfaceWrapper) CreateMember(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "householdId" -------------
	var householdId string

	err = runtime.BindStyledParameterWithOptions("simple", "householdId", chi.URLParam(r, "householdId"), &householdId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "householdId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateMember(w, r, householdId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteMember operation middleware
func (siw *ServerInterfaceWrapper) DeleteMember(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "householdId" -------------
	var householdId string

	err = runtime.BindStyledParameterWithOptions("simple", "householdId", chi.URLParam(r, "householdId"), &householdId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "householdId", Err: err})
		return
	}

	// ------------- Path parameter "memberId" -------------
	var memberId string

	err = runtime.BindStyledParameterWithOptions("simple", "memberId", chi.URLParam(r, "memberId"), &memberId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "memberId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMember(w, r, householdId, memberId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMember operation middleware
func (siw *ServerInterfaceWrapper) GetMember(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "householdId" -------------
	var householdId string

	err = runtime.BindStyledParameterWithOptions("simple", "householdId", chi.URLParam(r, "householdId"), &householdId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "householdId", Err: err})
		return
	}

	// ------------- Path parameter "memberId" -------------
	var memberId string

	err = runtime.BindStyledParameterWithOptions("simple", "memberId", chi.URLParam(r, "memberId"), &memberId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "memberId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMember(w, r, householdId, memberId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMember operation middleware
func (siw *ServerInterfaceWrapper) UpdateMember(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "householdId" -------------
	var householdId string

	err = runtime.BindStyledParameterWithOptions("simple", "householdId", chi.URLParam(r, "householdId"), &householdId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "householdId", Err: err})
		return
	}

	// ------------- Path parameter "memberId" -------------
	var memberId string

	err = runtime.BindStyledParameterWithOptions("simple", "memberId", chi.URLParam(r, "memberId"), &memberId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "memberId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMember(w, r, householdId, memberId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListFiscalPeriods operation middleware
func (siw *ServerInterfaceWrapper) ListFiscalPeriods(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "householdId" -------------
	var householdId string

	err = runtime.BindStyledParameterWithOptions("simple", "householdId", chi.URLParam(r, "householdId"), &householdId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "householdId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListFiscalPeriods(w, r, householdId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateFiscalPeriod operation middleware
func (siw *ServerInterfaceWrapper) CreateFiscalPeriod(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "householdId" -------------
	var householdId string

	err = runtime.BindStyledParameterWithOptions("simple", "householdId", chi.URLParam(r, "householdId"), &householdId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "householdId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateFiscalPeriod(w, r, householdId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LockFiscalPeriod operation middleware
func (siw *ServerInterfaceWrapper) LockFiscalPeriod(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "householdId" -------------
	var householdId string

	err = runtime.BindStyledParameterWithOptions("simple", "householdId", chi.URLParam(r, "householdId"), &householdId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "householdId", Err: err})
		return
	}

	// ------------- Path parameter "periodId" -------------
	var periodId string

	err = runtime.BindStyledParameterWithOptions("simple", "periodId", chi.URLParam(r, "periodId"), &periodId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "periodId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LockFiscalPeriod(w, r, householdId, periodId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBalanceSheet operation middleware
func (siw *ServerInterfaceWrapper) GetBalanceSheet(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "householdId" -------------
	var householdId string

	err = runtime.BindStyledParameterWithOptions("simple", "householdId", chi.URLParam(r, "householdId"), &householdId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "householdId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetBalanceSheetParams

	// ------------- Optional query parameter "as_of" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "as_of", r.URL.Query(), &params.AsOf, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "as_of"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "as_of", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBalanceSheet(w, r, householdId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetIncomeStatement operation middleware
func (siw *ServerInterfaceWrapper) GetIncomeStatement(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "householdId" -------------
	var householdId string

	err = runtime.BindStyledParameterWithOptions("simple", "householdId", chi.URLParam(r, "householdId"), &householdId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "householdId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetIncomeStatementParams

	// ------------- Required query parameter "after" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "after", r.URL.Query(), &params.After, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "after"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after", Err: err})
		}
		return
	}

	// ------------- Required query parameter "before" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "before", r.URL.Query(), &params.Before, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "before"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "before", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetIncomeStatement(w, r, householdId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/refresh", wrapper.RefreshToken)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/households/{householdId}", wrapper.GetHousehold)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/households/{householdId}", wrapper.UpdateHousehold)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/households/{householdId}/accounts", wrapper.ListAccounts)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/households/{householdId}/accounts", wrapper.CreateAccount)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/households/{householdId}/accounts/{accountId}", wrapper.GetAccount)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/households/{householdId}/accounts/{accountId}", wrapper.UpdateAccount)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/households/{householdId}/accounts/{accountId}/balance", wrapper.GetAccountBalance)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/households/{householdId}/entries", wrapper.ListJournalEntries)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/households/{householdId}/entries", wrapper.CreateJournalEntry)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/households/{householdId}/entries/{entryId}", wrapper.GetJournalEntry)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/households/{householdId}/entries/{entryId}/reverse", wrapper.ReverseJournalEntry)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/households/{householdId}/members", wrapper.ListMembers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/households/{householdId}/members", wrapper.CreateMember)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/households/{householdId}/members/{memberId}", wrapper.DeleteMember)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/households/{householdId}/members/{memberId}", wrapper.GetMember)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/households/{householdId}/members/{memberId}", wrapper.UpdateMember)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/households/{householdId}/periods", wrapper.ListFiscalPeriods)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/households/{householdId}/periods", wrapper.CreateFiscalPeriod)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/households/{householdId}/periods/{periodId}/lock", wrapper.LockFiscalPeriod)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/households/{householdId}/reports/balance-sheet", wrapper.GetBalanceSheet)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/households/{householdId}/reports/income-statement", wrapper.GetIncomeStatement)
	})

	return r
}
